# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Google Compute Engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  GCE_INSTANCE: ${{ secrets.GCE_DEV_INSTANCE }}
  GCE_INSTANCE_ZONE: asia-northeast3-a

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GCP_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy
        run: |-
          gcloud compute ssh "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            -- 'mkdir checking-folder'
